# Site settings
title: Sensu Plugins

support_email: support@sensuapp.org
users_email: sensu-users@googlegroups.com
dev_email: sensu-dev@googlegroups.com
irc: irc.freenode#sensu

sensu_twitter_username: sensuapp
sensu_plugin_org:  sensu-plugins
sensu_app_org: sensu

description: > # this means to ignore newlines until "baseurl:"
  The home for all Sensu Community plugins, handlers, and mutators.
license: > # this means to ignore newlines until "baseurl:"
  Copyright 2015 Sensu-Plugins and contributors.

baseurl: ''
url: 'http://sensu-plugins.github.io'


# Build settings
exclude: ["vendor"]
markdown:    kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM

gems:
  - jekyll-sitemap
  - jekyll-mentions

collections:
  docs:
    output: true

exclude_repos: ["GIR", "Kryten", "documentation", "sensu-plugin", "sensu-plugin-spec", "tom_servo", "sensu-plugins.github.io"]
