# Site settings
title: Sensu Plugins
email: support@sensuapp.org
irc: irc.freenode#sensu
description: > # this means to ignore newlines until "baseurl:"
  The home for all Sensu Official and Community plugins, handlers, extensions and mutators.
license: > # this means to ignore newlines until "baseurl:"
  Copyright 2011-2015 Sonian, Inc. and contributors.
baseurl: ''
url: 'http://sensu-plugins.github.io'
sensu_twitter_username: sensuapp
sensu_plugin_org:  sensu-plugins
sensu_app_org: sensu

# Build settings
markdown:    kramdown
highlighter: rouge

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
