# Site settings
title: Sensu Plugins

support_email: support@sensuapp.org
irc: irc.freenode#sensu

description: > # this means to ignore newlines until "baseurl:"
  The home for all Sensu Community plugins, handlers, and mutators. Open Source under MIT License.
license: > # this means to ignore newlines until "baseurl:"
  Copyright &copy; 2015-2016 Sensu-Plugins and contributors.

baseurl: ''
url: 'http://sensu-plugins.github.io'


# Build settings
exclude: ["vendor"]
markdown:    kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM

doc_cat: ["User", "Development", "Infrastructure"]

gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
collections:
  docs:
    output: true

exclude_repos: ["GIR", "Kryten", "documentation", "sensu-plugin", "sensu-plugin-spec", "tom_servo", "sensu-plugins.github.io", "mulder", "scully" ]
